# Generated by Django 5.2.2 on 2025-06-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorshipRequest',
        ),
    ]
