# Generated by Django 5.2.2 on 2025-06-15 02:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_email',
            field=models.EmailField(max_length=254, validators=[accounts.models.User.validate_thapar_email]),
        ),
    ]
