# Generated by Django 5.2.2 on 2025-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ResourceRating',
        ),
    ]
